[package]
name = "pipecolor"
version = "0.2.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/pipecolor"
categories = ["command-line-utilities", "value-formatting"]
license = "MIT"
readme = "README.md"
description = "A terminal filter to colorize output"

[badges]
travis-ci = { repository = "dalance/pipecolor" }
codecov   = { repository = "dalance/pipecolor", branch = "master", service = "github" }

[dependencies]
error-chain  = "0.11.0"
regex        = "0.2.10"
serde        = "1.0.33"
serde_derive = "1.0.33"
structopt    = "0.2.5"
termion      = "1.5.1"
toml         = "0.4.5"

[package.metadata.release]
dev-version-ext            = "pre"
pre-release-commit-message = "Prepare to v{{version}}"
pro-release-commit-message = "Start next development iteration v{{version}}"
tag-message                = "Bump version to {{version}}"
tag-prefix                 = "v"
