[package]
name = "colored"
version = "0.1.0"
authors = ["hatta"]

[dependencies]
error-chain  = "0.11.0"
regex        = "0.2.10"
serde        = "1.0.33"
serde_derive = "1.0.33"
structopt    = "0.2.5"
termion      = "1.5.1"
toml         = "0.4.5"
